name: Update stats card

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cicirello/user-statistician@v1
        with:
          image-file: assets/stats.svg
          colors: dark-dimmed
          include-title: false
          hide-keys: private
      - run: |
          git config user.name  "TabishNavaid"
          git config user.email "tabishnavaid06@gmail.com"
          git add assets/stats.svg
          git commit -m "Refresh stats card" || exit 0
          git push
