name: Update stats card

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate the stats image
        uses: cicirello/user-statistician@v1
        with:
          image-file: assets/stats.svg
          colors: "0d1a1c,2c4547,ffcf87,f4ece0,a9c4bd"
          include-title: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
